# XLA_PYTHON_CLIENT_MEM_FRACTION=0.5 python density_script.py --fun gen_traj
# XLA_PYTHON_CLIENT_MEM_FRACTION=0.5 python density_script.py --fun train
# XLA_PYTHON_CLIENT_MEM_FRACTION=0.5 python density_script.py --fun plot

###################################################################################################################
######################### These are the configurations when generating the dataset  ###############################
###################################################################################################################
seed_trans: 10

# Horizon when generating the data
# Thus, the total number of data is num_sample * (horizon + 1)
horizon: 50

# The possible noise setting configuration
noise_settings:
  LowNoise: 
    # pnoise: [0.001, 0.001] # Process noise
    mnoise: [0.0005, 0.001] # Measurement noise


sampling_domain_settings:
    DensityExp: 
      lb: [-0.15, -0.15]
      ub: [0.15, 0.15]

# Do not regenerate data file for existing file
regenerate: True

# List of number of sample for data generation
# Dataset are going to be generate for all the sampling and noise settings above
# num_samples: [6, 3, 1, 25]
num_samples: [6, 3, 25]
# num_samples: [6]

# This doesn't matter for the density eperiments as the training is done 
# on only the training dataset without fitting the data
test_data:
  num_samples: 10
  mnoise: [0.0001, 0.005]
  pnoise: null
  domain_lb: [0, 0]
  domain_ub: [0.1, 0.1]
  test_seed: 20


###################################################################################################################
####################### Modified parameters to use when training the density function #############################
###################################################################################################################
# grad_pen_range_values: [0., 1.0]
# ball_radius_range: [0.05, 0.1]
# mu_coeff_range: [1.0, 10.0, 100.0]
grad_pen_range_values: [1.0,]
ball_radius_range: [0.1,]
mu_coeff_range: [10,]


density_trainer:

  model:
    control_dependent_noise: False
    diffusion_density_nn:
      scaler_nn:
          type: none
          
      density_nn:
        init_value: 0.01
        activation_fn: swish
        # hidden_layers: [16, 16]
        hidden_layers: [64, 64]

  sde_loss:
    # Random seed for initializing the neural networks
    seed: 1
    # What stepsize to use when fitting the model to the data
    stepsize: 0.01
    # Number of particles when fitting the SDE -> If different to the default model num_particles
    num_particles: 1
    num_particles_test: 1
    # These two quantities are useless as we are just trying to fit the density function
    # This is the horizon of integration when computing the loss
    # It might get clipped to the horizon of each trajectory in the dataset if it's greater than trajectory length
    horizon: 50
    # Randomly subsample the horizon to fit only num_sample2consider if given
    num_sample2consider: 15

    # Density loss parameters
    density_loss:
      learn_mucoeff: False # Should we learn the local strong convexity parameters?
      mu_coeff: 10.0 # STrong convexity parameter
      ball_radius: 0.05 # THe radius of the ball to sample for enforcing local strong convexity
      ball_nsamples: 10 # Number of points to sample in the ball
      # grad_scaler: 1.0

    # Penalty for the error on the prediction
    pen_data: 0 # We remove it for density estimation

    # Penalty on the gradient of the density loss
    pen_grad_density: 0.0 # 0.01

    # Penalty on the local strong convexity constraints
    pen_density_scvex: 1.0

    # Regularization penalty default value for all parameters
    pen_weights: 0.0 #1.0e-6

    #########################################################################
    # Extra constraints parameterization
    #########################################################################
    default_weights: 1.0


  # Training configuration
  sde_optimizer:
    - name: scale_by_adam
    - name: linear_schedule
      scheduler: True
      params:
        init_value: -0.01 # Initial learning rate (Negative value for minimization)
        end_value: -0.001
        #transition_steps: 30000 # Basically the maximum number of gradient steps 
        transition_steps: 10000
    

  # Training parameters
  sde_training:
    train_batch: 512 # The mini batch size for the training dataset
    test_batch: 512 # The mini batch size for the training dataset
    # nepochs: 50000 # The number of epochs (full pass over the training dataset)
    nepochs: 150000
    patience: 40000 # The number of epochs after which to stop the learningif no improvement in solution
    test_freq: 50 # Number of gradient steps after which to evaluate and display losses
    save_freq: 500 # Number of gradient steps after which to save the current losses+nn
    # epochs_before_checking_improv: 10
    TestStopingCrit:
      TestErrorData: 0.0
      TestStdData: 0.0 # Maximime the noise of the learned SDE
    TrainStopingCrit:
      totalLoss: 1.0



###################################################################################################################
####################################### Mesh and plotting configuration  ##########################################
###################################################################################################################

# Range used for the mesh plot
qrange: [-0.25, 0.25]
qdotrange: [-0.25, 0.25]
# Number of grids on the axes
num_grid_q: 50
num_grid_qdot: 50

num_particles_diffusion: 1 # If the observation to state is nondeterministic, this is used

# Seed for operations related to the density estimation
seed_mesh: 10

training_dataset_config:
  label : 'Dataset'
  color : 'lavender'
  marker: 'x'
  markersize : 8 
  alpha : 1.0
  linestyle : 'None'
  zorder : 100

mesh_args:
  cmap: viridis
  shading: gouraud

colorbar_args:
  shrink: 0.95
  # extend: both
  pad: 0.01

extra_args:
  title_right_args:
    rotation: -90
    size: large
    labelpad: 15

################# Good ones ###################
# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 8]
#   nrows: 2
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True
# # mesh_specs:
# files2plot: 'GradXX_Rad0.05_Mu10__DensityExp_XX' # XX will be replaced by the values in plotconfig
# plot_configs:
#   - value: ['0','3']
#     title: '$N_{traj} = 3$'
#   - value: ['0','6']
#     title: '$N_{traj} = 6$'
#   - value: ['0','25']
#     title: '$N_{traj} = 25$'
#     title_right: '$\lambda_{grad} = 0$'

#   - value: ['1.0','3']
#   - value: ['1.0','6']
#   - value: ['1.0','25']
#     title_right: '$\lambda_{grad} = 1$'

# save_config:
#   fname: 'density_traj_vs_gradCost.png'
#   dpi: 500


# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 8]
#   nrows: 2
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True
# # mesh_specs:
# files2plot: 'GradXX_Rad0.05_MuXX__DensityExp_6' # XX will be replaced by the values in plotconfig
# plot_configs:
#   - value: ['0','1']
#     title: '$\mu_{conv} = 1$'
#   - value: ['0','10']
#     title: '$\mu_{conv} = 10$'
#   - value: ['0','100']
#     title: '$\mu_{conv} = 100$'
#     title_right: '$\lambda_{grad} = 0$'

#   - value: ['1.0','1']
#   - value: ['1.0','10']
#   - value: ['1.0','100']
#     title_right: '$\lambda_{grad} = 1$'

# save_config:
#   fname: 'density_mu_vs_gradCost_traj6.png'
#   dpi: 500

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 8]
#   nrows: 2
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True
# # mesh_specs:
# files2plot: 'GradXX_Rad0.05_MuXX__DensityExp_25' # XX will be replaced by the values in plotconfig
# plot_configs:
#   - value: ['0','1']
#     title: '$\mu_{conv} = 1$'
#   - value: ['0','10']
#     title: '$\mu_{conv} = 10$'
#   - value: ['0','100']
#     title: '$\mu_{conv} = 100$'
#     title_right: '$\lambda_{grad} = 0$'

#   - value: ['1.0','1']
#   - value: ['1.0','10']
#   - value: ['1.0','100']
#     title_right: '$\lambda_{grad} = 1$'

# save_config:
#   fname: 'density_mu_vs_gradCost_traj25.png'
#   dpi: 500

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 8]
#   nrows: 2
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True
# # mesh_specs:
# files2plot: 'GradXX_Rad0.05_MuXX__DensityExp_3' # XX will be replaced by the values in plotconfig
# plot_configs:
#   - value: ['0','1']
#     title: '$\mu_{conv} = 1$'
#   - value: ['0','10']
#     title: '$\mu_{conv} = 10$'
#   - value: ['0','100']
#     title: '$\mu_{conv} = 100$'
#     title_right: '$\lambda_{grad} = 0$'

#   - value: ['1.0','1']
#   - value: ['1.0','10']
#   - value: ['1.0','100']
#     title_right: '$\lambda_{grad} = 1$'

# save_config:
#   fname: 'density_mu_vs_gradCost_traj3.png'
#   dpi: 500

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 8]
#   nrows: 2
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True
# # mesh_specs:
# files2plot: 'Grad1.0_RadXX_Mu10__DensityExp_XX' # XX will be replaced by the values in plotconfig
# plot_configs:
#   - value: ['0.05','3']
#     title: '$N_{traj} = 3$'
#   - value: ['0.05','6']
#     title: '$N_{traj} = 6$'
#   - value: ['0.05','25']
#     title: '$N_{traj} = 25$'
#     title_right: '$B_{rad} = 0.05$'

#   - value: ['0.1','3']
#   - value: ['0.1','6']
#   - value: ['0.1','25']
#     title_right: '$B_{rad} = 0.1$'

# save_config:
#   fname: 'density_traj_vs_ballRad_mu10.png'
#   dpi: 500

# The list of models to plot in the configuration (usually a grid) they need to be plotted
fig_args:
  figsize: [14, 8]
  nrows: 2
  ncols: 3
  sharex: True
  sharey: True
  constrained_layout: True
# mesh_specs:
files2plot: 'Grad1.0_RadXX_Mu1__DensityExp_XX' # XX will be replaced by the values in plotconfig
plot_configs:
  - value: ['0.05','3']
    title: '$N_{traj} = 3$'
  - value: ['0.05','6']
    title: '$N_{traj} = 6$'
  - value: ['0.05','25']
    title: '$N_{traj} = 25$'
    title_right: '$B_{rad} = 0.05$'

  - value: ['0.1','3']
  - value: ['0.1','6']
  - value: ['0.1','25']
    title_right: '$B_{rad} = 0.1$'

save_config:
  fname: 'density_traj_vs_ballRad_mu1.png'
  dpi: 500