###################################################################################################################
####################################### Plotting and other configuration  #########################################
###################################################################################################################

# Range used for the mesh plot
qrange: [-0.25, 0.25]
qdotrange: [-0.25, 0.25]

# Number of grids on the axes
num_grid_q: 50
num_grid_qdot: 50

# Number of particles when computing uncertainties
num_particles_std: 100
horizon_pred_accuracy: 50
horizon_uncertainty: 5 # If not specified, it uses horizon_pred_accuracy

# If the observation to state is nondeterministic, this is used for density computation
num_particles_diffusion: 1

training_dataset_config:
  label : 'Dataset'
  color : 'lavender'
  marker: 'x'
  markersize : 8 
  alpha : 1.0
  linestyle : 'None'
  zorder : 100

# Seed for operation
seed: 10

# Mesh configuration
mesh_args:
  cmap: viridis
  shading: gouraud

colorbar_args:
  shrink: 0.95
  # extend: both
  pad: 0.01

extra_args:
  title_right_args:
    rotation: -90
    size: large
    labelpad: 15

# colors = ["black", "#E69F00", "#E69F00", "#56B4E9", "#56B4E9", "#D55E00", "#CC79A7", "#F0E442"]
general_style:
  linewidth: 2.0

curve_plot_style:
  groundtruth:
    label: "Groundtruth"
    color: "black"
    zorder: 100
  nesde:
    label: "Blackbox Neural SDE"
    color: "#E69F00"
    zorder: 30
  node:
    label: "Blackbox Neural ODE"
    color: "#56B4E9"
    zorder: 20
  dataset:
    label : 'Dataset'
    color : 'lavender'
    marker: 'x'
    markersize : 8 
    alpha : 0.3
    linestyle : 'None'
    zorder : 10

############################# Density mesh plots #########################################
##########################################################################################

# # Format for learned models to plot XX__MSD_XX_XX_XX
# # For example nesde__MSD_MeasLow_TopRight_5 according to the name of the learned models
# files2plot: 'nesde__MSD_MeasXX_XX_XX'

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 8]
#   nrows: 2
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True

# plot_configs:
#   - value: ['Low', 'TopRight', '5']
#     title: 'Low Meas Noise'
#     net: False
#   - value: ['High', 'TopRight', '5']
#     title: 'High Meas Noise'
#     net: False
#   - value: ['LowProcNoise', 'TopRight', '5']
#     title: 'Meas + Process Noise'
#     title_right: '$N_{traj} = 5$, Top Right'
#     net: False
  
#   - value: ['Low', 'FullSpace', '10']
#     net: False
#   - value: ['High', 'FullSpace', '10']
#     net: False
#   - value: ['LowProcNoise', 'FullSpace', '10']
#     title_right: '$N_{traj} = 10$, Full Space'
#     net: False

# save_config:
#   fname: 'density_nesde_dataset.png'
#   dpi: 500

# plot_configs:
#   - value: ['Low', 'TopRight', '5']
#     title: 'Low Meas Noise'
#     net: True
#   - value: ['High', 'TopRight', '5']
#     title: 'High Meas Noise'
#     net: True
#   - value: ['LowProcNoise', 'TopRight', '5']
#     title: 'Meas + Process Noise'
#     title_right: '$N_{traj} = 5$, Top Right'
#     net: True
  
#   - value: ['Low', 'FullSpace', '10']
#     net: True
#   - value: ['High', 'FullSpace', '10']
#     net: True
#   - value: ['LowProcNoise', 'FullSpace', '10']
#     title_right: '$N_{traj} = 10$, Full Space'
#     net: True

# save_config:
#   fname: 'density_nesde_dataset_nosig.png'
#   dpi: 500


############################ Uncertainty mesh plots #################################
#####################################################################################

# Format for learned models to plot XX__MSD_XX_XX_XX
# For example nestde__MSD_MeasLow_TopRight_5 according to the name of the learned models
# files2plot: 'XX__MSD_XX_XX_XX'

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   # Number of rows is automatically 2 for these uncertainty plots
#   figsize: [14, 8]
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True


# plot_configs:
#   - value: ['nesde','MeasLow','TopRight','5']
#     title: 'Low Meas Noise'
#   - value: ['nesde','MeasHigh','TopRight','5']
#     title: 'High Meas Noise'
#   - value: ['nesde','MeasLowProcNoise','TopRight','5']
#     title: 'Meas + Process Noise'
#   #   title: 'Density Neural net'

# save_config:
#   fname: 'uncertainty_nesde_topright_5.png'
#   dpi: 500

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   # Number of rows is automatically 2 for these uncertainty plots
#   figsize: [10, 8]
#   ncols: 2
#   sharex: True
#   sharey: True
#   constrained_layout: True


# plot_configs:
#   - value: ['nesde','MeasLow','TopRight','5']
#     title: 'Nesde model'
#   - value: ['node','MeasLow','TopRight','5']
#     title: 'NODE model'
#   #   title: 'Density Neural net'

# save_config:
#   fname: 'uncertainty_nesdeVsnode_lowMeas_topright_5.png'
#   dpi: 500


# plot_configs:
#   - value: ['nesde','MeasLowProcNoise','TopRight','5']
#     title: 'Nesde model'
#   - value: ['node','MeasLowProcNoise','TopRight','5']
#     title: 'NODE model'
#   #   title: 'Density Neural net'

# save_config:
#   fname: 'uncertainty_nesdeVsnode_lowProcMeas_topright_5.png'
#   dpi: 500


# plot_configs:
#   - value: ['nesde','MeasLow','TopRight','5']
#     title: 'Prior model'
#     prior_dist: True
#   - value: ['nesde','MeasLow','TopRight','5']
#     title: 'Nesde model'

# save_config:
#   fname: 'uncertainty_priorVsnesde_lowMeas_topright_5.png'
#   dpi: 500



############################ State evolution plots ###################################
######################################################################################

horizon_prediction: 1000
num_particles: 1000

# The percentiles used when plotting the sde distribution
alpha_percentiles: [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55]
percentiles_array: [0.999, 0.99, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]

init_config:
  - [-0.15, -0.15]
  - [0.1, 0.15]
  - [0.05, 0.07]

# Format for learned models to plot XX__MSD_XX_XX_XX
# For example nestde__MSD_MeasLow_TopRight_5 according to the name of the learned models
files2plot: 'XX__MSD_MeasXX_TopRight_5'

# The list of models to plot in the configuration (usually a grid) they need to be plotted
fig_args:
  figsize: [14, 10]
  nrows: 2
  ncols: 2
  # sharex: True
  # sharey: True
  constrained_layout: True


plot_configs:
  - value:
      - ['nesde', 'Low']
      - ['node', 'Low']
    style: ['nesde', 'node']
    type: "t2q" # q2qdot, 
    init: 0
    # show_xlabel: False
  
  - value:
      - ['nesde', 'Low']
      - ['node', 'Low']
    style: ['nesde','node']
    type: "t2qdot" # q2qdot, 
    init: 0
  
  - value:
      - ['nesde', 'Low']
      - ['node', 'Low']
    style: ['nesde', 'node']
    type: "q2qdot" # q2qdot, 
    init: 0
    # show_xlabel: False
  
  - value:
      - ['nesde', 'Low']
      - ['node', 'Low']
    style: ['nesde','node']
    type: "t2Err" # q2qdot, 
    init: 0

save_config:
  fname: 'state_nesdeVsnode_MeasLow_TopRight_5_ood.png'
  dpi: 500


# plot_configs:
#   - value:
#       - ['nesde', 'Low']
#       - ['node', 'Low']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 1
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'Low']
#       - ['node', 'Low']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 1
  
#   - value:
#       - ['nesde', 'Low']
#       - ['node', 'Low']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 1
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'Low']
#       - ['node', 'Low']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 1

# save_config:
#   fname: 'state_nesdeVsnode_MeasLow_TopRight_5_iid.png'
#   dpi: 500


# plot_configs:
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 1
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 1
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 1
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 1

# save_config:
#   fname: 'state_nesdeVsnode_MeasHigh_TopRight_5_iid.png'
#   dpi: 500

# plot_configs:
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 0
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 0

# save_config:
#   fname: 'state_nesdeVsnode_MeasHigh_TopRight_5_ood.png'
#   dpi: 500

# plot_configs:
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 0
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 0

# save_config:
#   fname: 'state_nesdeVsnode_MeasLowProcNoise_TopRight_5_ood.png'
#   dpi: 500

# plot_configs:
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 1
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 1
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 1
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 1

# save_config:
#   fname: 'state_nesdeVsnode_MeasLowProcNoise_TopRight_5_iid.png'
#   dpi: 500


#################
# files2plot: 'XX__MSD_MeasXX_FullSpace_10'

# plot_configs:
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 1
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 1
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 1
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 1

# save_config:
#   fname: 'state_nesdeVsnode_MeasLowProcNoise_FullSpace_10_iid.png'
#   dpi: 500

# plot_configs:
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 0
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'LowProcNoise']
#       - ['node', 'LowProcNoise']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 0

# save_config:
#   fname: 'state_nesdeVsnode_MeasLowProcNoise_FullSpace_10_ood.png'
#   dpi: 500

# plot_configs:
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 0
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 0

# save_config:
#   fname: 'state_nesdeVsnode_MeasHigh_FullSpace_10_ood.png'
#   dpi: 500

# plot_configs:
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde', 'node']
#     type: "t2q" # q2qdot, 
#     init: 2
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde','node']
#     type: "t2qdot" # q2qdot, 
#     init: 2
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde', 'node']
#     type: "q2qdot" # q2qdot, 
#     init: 2
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', 'High']
#       - ['node', 'High']
#     style: ['nesde','node']
#     type: "t2Err" # q2qdot, 
#     init: 2

# save_config:
#   fname: 'state_nesdeVsnode_MeasHigh_FullSpace_10_iid.png'
#   dpi: 500