###################################################################################################################
####################################### Plotting and other configuration  #########################################
###################################################################################################################
# JAX_PLATFORM_NAME=cpu python plot_dad_term.py --fun pred

############################# DAD term only #############################

# # Range used for the mesh plot
# thetarange: [-4.14, 4.14]
# thetadotrange: [-20, 20]
# # Number of grids on the axes
# num_grid_theta: 200
# num_grid_thetadot: 200

# num_particles_diffusion: 1 # If the observation to state is nondeterministic, this is used

# # Seed for operations related to the density estimation
# seed_mesh: 10

# training_dataset_config:
#   label : 'Dataset'
#   color : 'lavender'
#   marker: 'x'
#   markersize : 8 
#   alpha : 1.0
#   linestyle : 'None'
#   zorder : 100

# mesh_args:
#   cmap: viridis
#   shading: gouraud

# colorbar_args:
#   shrink: 0.95
#   # extend: both
#   pad: 0.01

# extra_args:
#   title_right_args:
#     rotation: -90
#     size: large
#     labelpad: 15

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [8, 8]
#   nrows: 1
#   ncols: 1
#   sharex: True
#   sharey: True
#   constrained_layout: True

# # # Plotting the neural network inside the density term or the density itself
# # net: True

# # Filename of the training dataset used for each model to plo
# train_data: 'learned.pkl'
# # vmin: 0
# # vmax: 0.2

# plot_configs:
#   - value: 'cartpole_bb_learned_v5_si_sde.pkl'
#     # train_data: 'learned.pkl'
#     title: 'Density on learned.pkl'

# save_config:
#   fname: 'dad_cartpole.png'
#   dpi: 500

#####################################################################
########### Plotting prediction error ############

# Evaluation dataset
eval_data: learned.pkl
num_traj_eval: 10 # NUmber of trajectory over which to estimate the prediction accuracy
# seed_traj_eval: 10 # Random seed for randomly pick the trajectory to evaluate
horizon_eval: 100 # Horizon of integration for prediction comparison
num_particles_eval: 50 # Number of particles for uncertainty
start_eval_strategy: first # first or random -> Strategy to pick the initial point in each trajectory selected

# The models to show on the plot
model2plot: [cartpole_bb_learned_sde, gaussian_mlp_ensemble_cartpole_random]
seed_eval: 15 # The seed for the probabilistic models: sde or jax
indx2plot: 5 # The trajectory in the list of picked trajectories to plot for displaying state evolution

# The percentiles used when plotting the sde distribution
# alpha_percentiles: [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
# percentiles_array: [0.999, 0.99, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.25]

alpha_percentiles: [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
percentiles_array: [0.75, 0.70, 0.65, 0.6, 0.55, 0.53, 0.5, 0.4, 0.3, 0.25]

# Which style to use for standardt deviation
# std_style: perc75 # std or minmax or perc (for percentiles)
alpha_std: 0.3

ylim: 
  - null
  - null
  - [-1.1, 1.1]
  - [-1.1, 1.1]
  - null

# Plot general configurations
general_style:
  linewidth: 2.0

# Plot specifc configuration dictionary
curve_plot_style:
  cartpole_bb_learned_sde:
    label: "SDE Model"
    # color: "#ff7f0e"
    color: "#d62728"
    color_std: "#d62728"
    zorder: 60
  gaussian_mlp_ensemble_cartpole_random:
    label: "Probabilistic Ensemble"
    color: "#2ca02c"
    color_std: "#2ca02c"
    std_style: perc
    linestyle: '--'
    zorder: 10
  # gaussian_mlp_ensemble_cartpole_learned_PPO_gt:
  #   label: "Policy tested in environment"
  #   color: "#d62728"
  #   color_std: "#d62728"
  #   zorder: 20
  # gaussian_mlp_ensemble_cartpole_learned_PPO:
  #   label: "Policy trained with learned PE"
  #   color: "#9467bd"
  #   color_std: "#9467bd"
  #   linestyle: '--'
  #   zorder: 10
  groundtruth:
    label: "Groundtruth"
    color: "#1f77b4"
    linestyle: '--'
    zorder: 80

extra_args:
  legend_args:
    loc: 'upper center'
    bbox_to_anchor: [0.5, 1.0]
    ncol: 3

# The grid configuration and extra figure parameters like spacing etc..
fig_args:
  figsize: [14, 8]


save_config:
  fname: 'Prediction_PIvsSDE.png'
  dpi: 500

# save_config_tex:
#   fname: 'gap_nosideinfo_vs_sideinfo.tex'


# ######################## Prediction uncertainty plot ############################

# model2plot: [cartpole_bb_learned_sde, gaussian_mlp_ensemble_cartpole_learned]

# curve_plot_style:
#   cartpole_bb_learned_sde:
#     title: SDE
#   gaussian_mlp_ensemble_cartpole_learned:
#     title: Probabilistic Ensemble

# # Range used for the mesh plot
# thetarange: [-3.9, 3.9]
# thetadotrange: [-15, 15]
# # Number of grids on the axes
# num_grid_theta: 100
# num_grid_thetadot: 100

# horizon_eval: 10
# num_particles_eval: 50

# # Seed for operations related to the density estimation
# seed_mesh: 10

# training_dataset_config:
#   label : 'Dataset'
#   color : 'lavender'
#   marker: 'x'
#   markersize : 8 
#   alpha : 1.0
#   linestyle : 'None'
#   zorder : 100

# mesh_args:
#   cmap: viridis
#   shading: gouraud

# colorbar_args:
#   shrink: 0.95
#   # extend: both
#   pad: 0.01

# extra_args:
#   title_right_args:
#     rotation: -90
#     size: large
#     labelpad: 15

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 6]
#   nrows: 1
#   ncols: 2
#   sharex: True
#   sharey: True
#   constrained_layout: True

# # # Normalize mesh
# # normalize_mesh: True

# # Filename of the training dataset used for each model to plo
# train_data: 'learned.pkl'

# # vmin: 0
# # vmax: 0.2


# save_config:
#   fname: 'uncertainty_PEvsSDE.png'
#   dpi: 500