###################################################################################################################
####################################### Plotting and other configuration  #########################################
###################################################################################################################

# Range used for the mesh plot
qrange: [-0.25, 0.25]
qdotrange: [-0.25, 0.25]

# Number of grids on the axes
num_grid_q: 50
num_grid_qdot: 50

# Number of particles when computing uncertainties
num_particles_std: 100
horizon_pred_accuracy: 50
horizon_uncertainty: 5 # If not specified, it uses horizon_pred_accuracy

# If the observation to state is nondeterministic, this is used for density computation
num_particles_diffusion: 1

training_dataset_config:
  label : 'Dataset'
  color : 'lavender'
  marker: 'x'
  markersize : 8 
  alpha : 1.0
  linestyle : 'None'
  zorder : 100

# Seed for operation
seed: 10

# Mesh configuration
mesh_args:
  cmap: viridis
  shading: gouraud

colorbar_args:
  shrink: 0.95
  # extend: both
  pad: 0.01

extra_args:
  title_right_args:
    rotation: -90
    size: large
    labelpad: 15

# colors = ["black", "#E69F00", "#E69F00", "#56B4E9", "#56B4E9", "#D55E00", "#CC79A7", "#F0E442"]
general_style:
  linewidth: 2.0

curve_plot_style:
  groundtruth:
    label: "Groundtruth"
    color: "black"
    zorder: 100
  nesde:
    label: "Blackbox Neural SDE"
    color: "#E69F00"
    zorder: 30
  node:
    label: "Blackbox Neural ODE"
    color: "#56B4E9"
    zorder: 20
  dataset:
    label : 'Dataset'
    color : 'lavender'
    marker: 'x'
    markersize : 8 
    alpha : 0.3
    linestyle : 'None'
    zorder : 10
  nesde_err:
    label: "Blackbox Neural SDE"
    color: "#E69F00"
    zorder: 20
    marker: 'o'
    markersize: 8
  node_err:
    label: "Blackbox Neural ODE"
    color: "#56B4E9"
    zorder: 30
    marker: 'o'
    markersize: 8

############################# Density mesh plots #########################################
##########################################################################################

# # Format for learned models to plot XX__MSD_XX_XX_XX
# # For example nesde__MSD_MeasLow_TopRight_5 according to the name of the learned models
# files2plot: 'nesde__MSD_MeasXX_XX_XX'

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 8]
#   nrows: 2
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True

# plot_configs:
#   - value: ['Low', 'TopRight', '5']
#     title: 'Low Meas Noise'
#     net: False
#   - value: ['High', 'TopRight', '5']
#     title: 'High Meas Noise'
#     net: False
#   - value: ['LowProcNoise', 'TopRight', '5']
#     title: 'Meas + Process Noise'
#     title_right: '$N_{traj} = 5$, Top Right'
#     net: False
  
#   - value: ['Low', 'FullSpace', '10']
#     net: False
#   - value: ['High', 'FullSpace', '10']
#     net: False
#   - value: ['LowProcNoise', 'FullSpace', '10']
#     title_right: '$N_{traj} = 10$, Full Space'
#     net: False

# save_config:
#   fname: 'density_nesde_dataset.png'
#   dpi: 500

# plot_configs:
#   - value: ['Low', 'TopRight', '5']
#     title: 'Low Meas Noise'
#     net: True
#   - value: ['High', 'TopRight', '5']
#     title: 'High Meas Noise'
#     net: True
#   - value: ['LowProcNoise', 'TopRight', '5']
#     title: 'Meas + Process Noise'
#     title_right: '$N_{traj} = 5$, Top Right'
#     net: True
  
#   - value: ['Low', 'FullSpace', '10']
#     net: True
#   - value: ['High', 'FullSpace', '10']
#     net: True
#   - value: ['LowProcNoise', 'FullSpace', '10']
#     title_right: '$N_{traj} = 10$, Full Space'
#     net: True

# save_config:
#   fname: 'density_nesde_dataset_nosig.png'
#   dpi: 500


############################ Uncertainty mesh plots #################################
#####################################################################################

# Format for learned models to plot XX__MSD_XX_XX_XX
# For example nestde__MSD_MeasLow_TopRight_5 according to the name of the learned models
# files2plot: 'XX__MSD_XX_XX_XX'

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   # Number of rows is automatically 2 for these uncertainty plots
#   figsize: [14, 8]
#   ncols: 3
#   sharex: True
#   sharey: True
#   constrained_layout: True


# plot_configs:
#   - value: ['nesde','MeasLow','TopRight','5']
#     title: 'Low Meas Noise'
#   - value: ['nesde','MeasHigh','TopRight','5']
#     title: 'High Meas Noise'
#   - value: ['nesde','MeasLowProcNoise','TopRight','5']
#     title: 'Meas + Process Noise'
#   #   title: 'Density Neural net'

# save_config:
#   fname: 'uncertainty_nesde_topright_5.png'
#   dpi: 500

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   # Number of rows is automatically 2 for these uncertainty plots
#   figsize: [10, 8]
#   ncols: 2
#   sharex: True
#   sharey: True
#   constrained_layout: True


# plot_configs:
#   - value: ['nesde','MeasLow','TopRight','5']
#     title: 'Nesde model'
#   - value: ['node','MeasLow','TopRight','5']
#     title: 'NODE model'
#   #   title: 'Density Neural net'

# save_config:
#   fname: 'uncertainty_nesdeVsnode_lowMeas_topright_5.png'
#   dpi: 500


# plot_configs:
#   - value: ['nesde','MeasLowProcNoise','TopRight','5']
#     title: 'Nesde model'
#   - value: ['node','MeasLowProcNoise','TopRight','5']
#     title: 'NODE model'
#   #   title: 'Density Neural net'

# save_config:
#   fname: 'uncertainty_nesdeVsnode_lowProcMeas_topright_5.png'
#   dpi: 500


# plot_configs:
#   - value: ['nesde','MeasLow','TopRight','5']
#     title: 'Prior model'
#     prior_dist: True
#   - value: ['nesde','MeasLow','TopRight','5']
#     title: 'Nesde model'

# save_config:
#   fname: 'uncertainty_priorVsnesde_lowMeas_topright_5.png'
#   dpi: 500



############################ State evolution plots ###################################
######################################################################################

err_radius: [0.02, 0.02, 0.01, 0.01]
err_num_points: 20

horizon_prediction: 2500
num_particles: 1000

# The percentiles used when plotting the sde distribution
alpha_percentiles: [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55]
percentiles_array: [0.999, 0.99, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]

init_config:
  # - [-0.1, 0.2, 0.2, -0.2] # SHow limitations
  # - [0.2, 0.2, 0.2, -0.2]
  # - [-0.02, 0.02, 0.1, 0.1]
  # - [-0.02, 0.02, 0.01, 0.01]
  - [-0.02, 0.02, 0.01, 0.01]

# Format for learned models to plot XX__MSD_XX_XX_XX
# For example nestde__MSD_MeasLow_TopRight_5 according to the name of the learned models
files2plot: 'XX__DoPe_MeasLow_TopLeft_15'

# The list of models to plot in the configuration (usually a grid) they need to be plotted
fig_args:
  figsize: [14, 10]
  nrows: 2
  ncols: 2
  sharex: True
  # sharey: True
  constrained_layout: True

# plot_configs:
#   - value:
#       - ['nesde', ]
#       - ['node',]
#     style: ['nesde', 'node']
#     type: "t2q1" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', ]
#       - ['node',]
#     style: ['nesde', 'node']
#     type: "t2q2" # q2qdot, 
#     init: 0
  
#   - value:
#       - ['nesde', ]
#       - ['node',]
#     style: ['nesde', 'node']
#     type: "t2q1dot" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde', ]
#       - ['node',]
#     style: ['nesde', 'node']
#     type: "t2Err" # q2qdot, 
#     init: 0

plot_configs:
  - value:
      - ['nesde_phys_v2', ]
      - ['node_phys_v2',]
    style: ['nesde', 'node']
    type: "t2q1" # q2qdot, 
    init: 0
    # show_xlabel: False
  
  - value:
      - ['nesde_phys_v2', ]
      - ['node_phys_v2',]
    style: ['nesde', 'node']
    type: "t2q2" # q2qdot, 
    init: 0
  
  - value:
      - ['nesde_phys_v2', ]
      - ['node_phys_v2',]
    style: ['nesde', 'node']
    type: "t2q1dot" # q2qdot, 
    init: 0
    # show_xlabel: False
  
  - value:
      - ['nesde_phys_v2', ]
      - ['node_phys_v2',]
    style: ['nesde', 'node']
    type: "t2Err" # q2qdot, 
    init: 0

# plot_configs:
#   - value:
#       - ['nesde_phys_v2', ]
#       - ['nesde',]
#     style: ['nesde', 'node']
#     type: "t2q1" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde_phys_v2', ]
#       - ['nesde',]
#     style: ['nesde', 'node']
#     type: "t2q2" # q2qdot, 
#     init: 0
  
#   - value:
#       - ['nesde_phys_v2', ]
#       - ['nesde',]
#     style: ['nesde', 'node']
#     type: "t2q1dot" # q2qdot, 
#     init: 0
#     # show_xlabel: False
  
#   - value:
#       - ['nesde_phys_v2', ]
#       - ['nesde',]
#     style: ['nesde', 'node']
#     type: "t2Err" # q2qdot, 
#     init: 0

save_config:
  fname: 'state_nesdeVsnode_MeasLow_TopRight_5_ood.png'
  dpi: 500

# ####################################################################################
# ######################### Show dataset and save it for vizu ########################

# files2plot: 'DoPe_MeasLow_TopLeft_XX'
# data_ids: ['1', '3', '8', '15']

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 10]
#   sharex: True
#   # sharey: True
#   # constrained_layout: True

# save_config:
#   dpi: 500


############################# Sample efficiency plot ####################################
##########################################################################################

# data_ids: ['1', '3', '8', '15']
# # err_radius: [0.02, 0.02, 0.01, 0.01]
# err_radius: [0.05, 0.05, 0.1, 0.1]
# err_num_points: 20

# horizon_prediction: 1500
# num_particles: 100

# init_config:
#   - [-0.1, -0.1, 0.4, -0.4]
#   - [-0.1, -0.1, -0.1, -0.1] # uncertainty -> outside ish
#   # - [-0.1, 0.2, 0.2, -0.2] # SHow limitations
#   # - [0.2, 0.2, 0.2, -0.2]
#   # - [-0.02, 0.02, 0.1, 0.1]
#   - [-0.02, 0.02, 0.01, 0.01]
#   - [-0.02, 0.02, 0.01, 0.01]

# files2plot: 'XX__DoPe_MeasLow_TopLeft_XX'

# # The list of models to plot in the configuration (usually a grid) they need to be plotted
# fig_args:
#   figsize: [14, 10]
#   nrows: 2
#   ncols: 3
#   sharex: True
#   # sharey: True
#   constrained_layout: True

# plot_configs:
#   - models: ['nesde', 'node']
#     style: ['nesde_err', 'node_err']
#     type: "traj2error"
#     init: 0
#     title: "Black boxes models"
#     show_xlabel: False
#     axis_constraints:
#       set_ylim:
#         ymin: 0.0025
#         ymax: 0.2
  
#   - models: ['nesde_phys_v2', 'node_phys_v2']
#     style: ['nesde_err', 'node_err']
#     type: "traj2error"
#     title: "Side information Lvl 1"
#     init: 0
#     show_xlabel: False
#     show_ylabel: False
#     axis_constraints:
#       set_ylim:
#         ymin: 0.0025
#         ymax: 0.2

#   - models: ['nesde_phys1', 'node_phys1']
#     style: ['nesde_err', 'node_err']
#     type: "traj2error"
#     init: 0
#     title: "Side information Lvl 2"
#     show_xlabel: False
#     show_ylabel: False
#     axis_constraints:
#       set_ylim:
#         ymin: 0.0025
#         ymax: 0.2
  
#   - models: ['nesde',]
#     style: ['nesde_err',]
#     type: "traj2std"
#     init: 0
  
#   - models: ['nesde_phys_v2',]
#     style: ['nesde_err',]
#     type: "traj2std"
#     init: 0
#     show_ylabel: False
  
#   - models: ['nesde_phys1',]
#     style: ['nesde_err',]
#     type: "traj2std"
#     init: 0
#     show_ylabel: False


# save_config:
#   fname: 'state_nesdeVsnode_MeasLow_TopRight_5_ood.png'
#   dpi: 500